mydjango/accounts/urls.py
from django.urls import path
from accounts import views


# 경로 앱 이름 지정 'accounts:index 앱 name 역할을 한다.'
app_name = 'accounts'


# accounts/@@@
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('delete/', views.delete, name='delete'),

    # Path Converter  <꺽쇠>
    # str : /(슬래시)를 제외한 모든 문자열과 매치된다. 타입이 지정되지 않았다면 디폴트로 str 타입을 사용한다.
    # int : 0 또는 양의 정수와 매치된다. 매치된 정수는 python 의 int 타입으로 변환된다.
    # slug : slug 형식의 문자열(ASCII, 숫자, 하이픈, 밑줄로만 구성됨)과 매치된다.
    # uuid : UUID 형식의 문자열과 매치된다. 매치된 문자열은 python 의 UUID 타입으로 변환된다.
    # path : /(슬래시)를 포함한 모든 문자열과 매치된다. 이는 URL 패턴의 일부가 아니라 전체를 추출하고자 할때 많이 사용한다.
]

mydjango/boards/urls.py
from django.urls import path
from boards import views

# 경로 앱 이름 지정 'boards:detail'
app_name = 'boards'

# boards/
urlpatterns = [
    # boards
    path('', views.index, name='index'),  # boards/  # 첫 화면
    path('<int:board_pk>/', views.detail, name='detail'),  # boards/@/
    path('create/', views.create, name='create'),  # boards/create/
    path('<int:board_pk>/delete/', views.delete, name='delete'),  # boards/@/delete/
    path('<int:board_pk>/update/', views.update, name='update'),  # boards/@/update/

    # comments
    # POST /boards/@/comments
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),  # boards/@/comments/
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),  # boards/@/comments/@/delete/

    # like & dislike
    path('<int:board_pk>/like/', views.like, name='like'),  # 특정 게시글 좋아요 path  # boards/@/like/
    path('<int:board_pk>/dislike/', views.dislike, name='dislike'),  # 특정 게시글 좋아요 path  # boards/@/dislike/

    # follow
    path('<int:board_pk>/follow/<int:user_pk>/', views.follow, name='follow'),  # boards/@/follow/@/

    # Path Converter  <꺽쇠>
    # str : /(슬래시)를 제외한 모든 문자열과 매치된다. 타입이 지정되지 않았다면 디폴트로 str 타입을 사용한다.
    # int : 0 또는 양의 정수와 매치된다. 매치된 정수는 python 의 int 타입으로 변환된다.
    # slug : slug 형식의 문자열(ASCII, 숫자, 하이픈, 밑줄로만 구성됨)과 매치된다.
    # uuid : UUID 형식의 문자열과 매치된다. 매치된 문자열은 python 의 UUID 타입으로 변환된다.
    # path : /(슬래시)를 포함한 모든 문자열과 매치된다. 이는 URL 패턴의 일부가 아니라 전체를 추출하고자 할때 많이 사용한다.
]

mydjango/boards/models.py
from django.db import models
from django.conf import settings


class Board(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # N : M 관계
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_boards',  # 다대다 관계 설정
        blank=True,  # 게시글을 좋아하는 사람이 없을 수도 있으니 blank=True
    )
    # related_name='like_boards 를 설정하지 않는다면
    # user.board_set.all() 에서 장고는 1. 내가 지금까지 작성한 게시글, 2. 내가 좋아요 한 게시글 2개 무엇을 가져와야할지 모른다.
    # 그래서
    # user.board_set.all() 은 1. 내가 지금까지 작성한 게시글을 표시
    # user.like_boards.all() 은 2. 내가 좋아요 한 게시글을 표시
    # 이렇게 지정해줘야 한다.
    dislike_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='dislike_boards',  # 다대다 관계 설정
        blank=True,  # 게시글을 좋아하는 사람이 없을 수도 있으니 blank=True
    )

    # 데이터 표현식 변경
    def __str__(self):
        return f'{self.pk}, {self.title}'


class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.content}'

mydjango/boards/forms.py
from django import forms
from .models import Board, Comment


class BoardForm(forms.ModelForm):
    #  Form 에 대한 정보들 입력
    title = forms.CharField(
        max_length=20,
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'title',
                'placeholder': 'Enter the title',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'rows': 5,
                'cols': 50,
                'placeholder': 'Enter the content',
                'class': 'content-type',
            }
        )
    )

    #  Model 의 대한 정보들 입력
    class Meta:
        model = Board
        fields = ('title', 'content', )


class CommentForm(forms.ModelForm):
    content = forms.CharField(label=False)

    class Meta:
        model = Comment
        fields = ('content', )

mydjango/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET, require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from boards.models import Board, Comment
from boards.forms import BoardForm, CommentForm


# 사이트/boards 첫 화면
@require_GET
def index(request):  # 클라이언트의 request 요청을 받겠다.
    boards = Board.objects.order_by('-pk')  # 게시판 등록된 글을 내림차순으로  # 오름차순은 order_by('pk')
    context = {'boards': boards}
    return render(request, 'boards/index.html', context)  # 클라이언트의 request 를 boards/index.html 로 보내고 context 도 보낸다.


# 로그인한 사용자에 한해 게시글 등록 기능 구현
@login_required  # 로그인 상태에서만 아래 함수 접속 및 처리
@require_http_methods(['GET', 'POST'])  # GET 과 POST 만 받겠다 라는 의미
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)  # 바로 저장하지 않고
            board.user = request.user        # 유저값을 대입한 뒤
            board = form.save()              # 저장한다.
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm()
    context = {'form': form}
    return render(request, 'boards/form.html', context)


# 게시글 상세 보기 기능 구현
# boards/3/
@require_GET  # GET 만 받겠다 라는 의미
def detail(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    #  Board 를 참조하고 있는 모든 댓글
    comments = board.comment_set.order_by('-pk')
    comment_form = CommentForm()
    person = get_object_or_404(get_user_model(), pk=board.user_id)
    context = {
        'board': board,
        'comment_form': comment_form,
        'comments': comments,
        'person': person,
    }
    return render(request, 'boards/detail.html', context)


# 게시글 삭제 기능 구현
# POST boards/3/delete/
@require_POST
def delete(request, board_pk):
    # 특정 보드를 불러와서 삭제한다.
    board = get_object_or_404(Board, pk=board_pk)
    # 요청을 보낸 유저와 게시글의 작성자가 같을때만 삭제
    if request.user != board.user:
        return redirect('boards:detail', board_pk)
    board.delete()
    return redirect('boards:index')


# 로그인한 사용자에 한해 글 수정 기능 구현
@login_required  # 로그인 상태에서만 아래 함수 접속 및 처리
@require_http_methods(['GET', 'POST'])  # GET 과 POST 만 받겠다 라는 의미
def update(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    # 원작자가 작성한 게시글을 다른사람이 수정하지 못하게 하는 처리
    # request.user : 요청을 보내는 사용자, board.user : 게시글 수정을 하는 사용자
    if request.user != board.user:
        return redirect('boards:detail', board_pk)
    #  POST boards/3/update/
    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)  # 바로 저장하지 않고
            board.user = request.user        # 유저값을 대입한 뒤
            board = form.save()              # 저장한다.
            return redirect('boards:detail', board.pk)
    #  GET boards/3/update/
    else:
        form = BoardForm(instance=board)  # board 데이터 할당
    context = {
        'form': form,
        'board_pk': board_pk,
    }
    return render(request, 'boards/form.html', context)


# 댓글 등록 기능 구현
@require_POST  # POST 만 받겠다 라는 의미
def comments_create(request, board_pk):
    # 로그인하지 않은 사용자 차단
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    # 댓글 작성 로직
    comment_form = CommentForm(request.POST)  # model form 에 사용자 입력을 받는다.
    # 유효성 검사
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
    # 유저 정보 할당
        comment.user = request.user
        # 같은 말 comment.user_id = request.user.id
    # board 정보 할당
        comment.board_id = board_pk  # pk 로 할당
    # 저장
        comment.save()

    return redirect('boards:detail', board_pk)


# 댓글 삭제 기능 구현
@require_POST  # POST 만 받겠다 라는 의미
def comments_delete(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if comment.user == request.user:
        comment.delete()
    # 댓글 삭제 로직
    return redirect('boards:detail', board_pk)


# '좋아요' 기능 구현
# '좋아요'와 '좋아요 취소'를 함수 2개로 만들어도 되지만 한개의 like 에서 if 문을 사용해서 분기 처리하는게 좋다.
@login_required()
def like(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    user = request.user
    # board 를 좋아요 누른 모든 사람중에서 user 가 있다면
    if user in board.like_users.all():
        board.like_users.remove(user)  # 좋아요 해제
    else:  # 아니라면
        board.like_users.add(user)  # 좋아요 추가
    return redirect('boards:detail', board_pk)


# '싫어요' 기능 구현
# '싫어요'와 '싫어요 취소'를 함수 2개로 만들어도 되지만 한개의 dislike 에서 if 문을 사용해서 분기 처리하는게 좋다.
def dislike(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    user = request.user
    # board 를 싫어요 누른 모든 사람중에서 user 가 있다면
    if user in board.dislike_users.all():
        board.dislike_users.remove(user)  # 싫어요 해제
    else:  # 아니라면
        board.dislike_users.add(user)  # 싫어요 추가
    return redirect('boards:detail', board_pk)


# '팔로우' 기능 구현
@login_required
def follow(request, board_pk, user_pk):
    user = request.user
    person = get_object_or_404(get_user_model(), pk=user_pk)

    if user != person:
        if user in person.followers.all():
            person.followers.remove(user)
        else:
            person.followers.add(user)
    return redirect('boards:detail', board_pk)

mydjango/boards/templates/boards/_profile.html
<div class="jumbotron text-center">
    <p class="lead mb-1">작성자 정보</p>
    <h1 class="display-4">{{ board.user }}</h1>
    <hr />
    <p class="lead">
        팔로잉 : {{ person.followings.all | length }} / 팔로워 : {{ person.followers.all | length }}
    </p>
    {% if person != user %}
        <a href="{% url 'boards:follow' board.pk board.user_id %}" class="btn btn-primary btn-lg">
            {% if user in person.followers.all %}
            Unfollow
            {% else %}
            Follow
            {% endif %}
        </a>
    {% endif %}
</div>

mydjango/boards/templates/boards/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% bootstrap_css %}
    <script src="https://kit.fontawesome.com/f788185e0b.js"></script>
    <title>강민호 포트폴리오</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

mydjango/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}

{% block body %}
<!-- Right-aligned nav -->
    <ul class="nav justify-content-end">
{% if user.is_authenticated %} <!--만약 사용자가 로그인 되어 있다면 -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'boards:index' %}">게시글 목록</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'boards:create' %}">게시글 작성</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:update' %}">마이페이지</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
    </ul>
{% else %}  <!--비회원이라면 -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
      </li>
    </ul>
{% endif %}

    <h1>Detail</h1>
    <hr />
    {% include 'boards/_profile.html' %}
    <p><b>글 번호:</b> {{ board.pk }}</p>
    <p><b>글 제목:</b> {{ board.title }}</p>
    <p><b>글 내용:</b> {{ board.content }}</p>
    <p><b>글 생성시각:</b> {{ board.created_at }}</p>
    <p><b>글 수정시각:</b> {{ board.updated_at }}</p>

    <a class="text-danger" href="{% url 'boards:like' board.pk %}">
        {% if user in board.like_users.all %}
        <i class="far fa-thumbs-up"></i>
        {% else %}
        <i class="far fa-thumbs-up"></i>
        {% endif %}
    </a>
    {{ board.like_users.all | length }}명이 좋아합니다.

    <a class="text-success" href="{% url 'boards:dislike' board.pk %}">
        {% if user in board.dislike_users.all %}
        <i class="far fa-thumbs-down"></i>
        {% else %}
        <i class="far fa-thumbs-down"></i>
        {% endif %}
    </a>
    {{ board.dislike_users.all | length }}명이 싫어합니다.

    <hr />

    <h4>댓글 목록</h4>
    {% for comment in comments %}
    <div>
        {% if request.user == comment.user %}
        <strong>댓글 작성자: {{ comment.user }}</strong>
        <span class="ml-3">댓글 내용: {{ comment.content }}</span>
        <form class="d-inline ml-4" action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-link text-danger" type="submit" value="댓글삭제">
        </form>
        {% endif %}
    </div>

    {% empty %}
    <p>아직 댓글이 없습니다.</p>
    {% endfor %}

    {% if user.is_authenticated %}
    <form class="mt-3" action="{% url 'boards:comments_create' board.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form comment_form %}
        <input class="btn btn-primary" type="submit" value="댓글등록">
    </form>
    {% else %}
    <br />
    <p>댓글을 작성하려면 <a href="{% url 'accounts:login' %}">로그인</a></p>
    {% endif %}
    <hr />

    {% if user == board.user %}  <!-- 요청을 보내는 유저가 게시글의 유저일때만 수정하기 버튼 보이게 처리 {# if user.is_authenticated #} -->
    <form class="d-inline" action="{% url 'boards:delete' board.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="삭제하기" />
    </form>
    <a class="btn btn-warning" href="{% url 'boards:update' board.pk %}">수정하기</a>
    {% endif %}
    <a class="btn btn-secondary" href="{% url 'boards:index' %}">뒤로가기</a>
{% endblock %}

mydjango/boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}

{% block body %}
    {% if request.resolver_match.url_name == 'create' %}
    <h1>새로운 게시글 작성</h1>
    {% else %} <!-- Update 가 들어오면 -->
    <h1>게시글 수정</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit="등록" reset="취소" %}
        {% endbuttons %}
    </form>
    {% if request.resolver_match.url_name == 'create' %}
    <a class="btn btn-secondary" href="{% url 'boards:index' %}">뒤로가기</a>
    {% else %}
    <a class="btn btn-secondary" href="{% url 'boards:detail' board_pk %}">뒤로가기</a>
    {% endif %}
{% endblock %}

mydjango/boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% block body %}
<!-- Right-aligned nav -->
    <ul class="nav justify-content-end">
{% if user.is_authenticated %} <!--만약 사용자가 로그인 되어 있다면 -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'boards:index' %}">게시글 목록</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'boards:create' %}">게시글 작성</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:update' %}">마이페이지</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
    </ul>
{% else %}  <!--비회원이라면 -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
      </li>
    </ul>
{% endif %}

<div class="jumbotron">
    <h1>게시글 목록</h1>
    {% if user.is_authenticated %}  <!--사용자 로그인했다면 True, 아니라면 False-->
        <h3>{{ user.username }}님 안녕하세요!</h3>
        <a class="btn btn-danger" href="{% url 'boards:create' %}">게시글 작성</a>
    {% else %}
        <p>새 글을 쓰려면 <b><a href="{% url 'accounts:login' %}">로그인</a></b>하세요.</p>
    {% endif %}
</div>

{% for board in boards %}
    <div class="card">
        <div class="card-body">
            <!--  1. 첫번째 글  -->
            <p>{{ board.pk }}. {{board.title}}</p>
            <a class="btn btn-info" href="{% url 'boards:detail' board.pk %}">글 상세보기</a>
        </div>
    </div>
    <br />
{% empty %}
    <p><strong>아직 작성된 글이 없습니다.</strong></p>
{% endfor %}

{% endblock %}